default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: e4nier-me_development

test:
  <<: *default
  database: e4nier-me_test

production:
  <<: *default
  database: e4nier-me_production
  username: e4nier-me
  password: <%= ENV['E4NIER-ME_DATABASE_PASSWORD'] %>
